// configparser.h
#include "../../include/configparser.h"
#include <time.h>

ConfigParser::ConfigParser(File* f) {
        set_fail(true);
        // Get contents of file
        std::string filecontents = f->getContents();
        auto c = std::clock();
        try {
            object = json::parse(filecontents);
        }
        catch(...) {
            error = "An exception was thrown during parsing of JSON data";
            return;
        }
        try {
            std::exception e;
            if(!object["repos"].is_array()) throw e;
        }
        catch(std::exception& e){
            error = "LightSpeed seems to have a configuration error. Check the configuration file for potential typos or mistakes. If the config file was generated by LightSpeed, report the bug on our Github page";
            return;
        }
        auto time_elapsed = double(std::clock() - c);
        json repo_list = object["repos"];
        for (auto r : repo_list) {
            repos.push_back(r);
        }
        double sec = time_elapsed / CLOCKS_PER_SEC;
        std::cout.precision(10);
        std::cout << "Configuration file loaded in " << sec<< " seconds"<< std::endl;
        set_fail(false);
    }
    

bool ConfigParser::success() {
        return !did_fail();
    }
    
std::string ConfigParser::error_msg() {
        return error;
    }
    
std::vector<std::string> ConfigParser::get_repos() {
    return repos;
}

ProjectFileParser::ProjectFileParser(File* f) {
        std::string contents = f->getContents();
        try {
            object = json::parse(contents);
        }
        catch(...) {
            error_msg = "An exception was thrown during parsing of the JSON data";
            return;
        }
        try {
            std::exception e;
            if(!(object["name"].is_string())) throw e;
            if(!(object["version"].is_string())) throw e;
            if(!(object["owner"].is_string())) throw e;
        }
        catch (std::exception& e) {
            std::cout<<"B";
            error_msg = "There was an error parsing your package definition file. Check the file for typos";
            return;
        }
        name = object["name"];
        version = object["version"];
        owner = object["owner"];
        json deproot = object["dependencies"];
        if (!deproot.is_array()) {
            error_msg = "There was an error parsing the dependencies for your project. Make sure they are formatted correctly";
            return;
        }
        for (auto package : deproot) {
            dependencies.push_back(package);
        }
    }
    
std::string ProjectFileParser::get_error() {
    return error_msg;
}
